contacts/urls.py
from django.urls import path

from . import views


app_name = 'contacts'
urlpatterns = [
    path('', views.index, name='index'),
    path('person/', views.PersonList.as_view(), name='person'),
    path('person/<int:pk>', views.PersonDetail.as_view(), name='persondetail'),
    path('company/', views.CompanyList.as_view(), name='company'),
    path('company/<int:pk>', views.CompanyDetail.as_view(), name='companydetail')
]

gsistcrm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('', include('contacts.urls')),
    path('admin/', admin.site.urls),
    # path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

contacts/models.py
# Django
from django.db import models

# Contrib, 3rd Party
from django_countries.fields import CountryField


class Contact(models.Model):
    """Abstract Main Contact Model."""

    address_line = models.CharField('address', max_length=250)
    city = models.CharField('city', max_length=60)
    state = models.CharField('state', max_length=30)
    postcode = models.CharField('post code', max_length=8, blank=True)
    country = CountryField('country')

    phone_number = models.CharField('phone number', max_length=12, blank=True)
    fax = models.CharField('fax', max_length=12, blank=True)
    mobile_number = models.CharField('mobile number', max_length=12, blank=True)

    web = models.URLField('web url', blank=True)
    email = models.EmailField('e-mail', max_length=254, blank=True)

    # owner = models.ForeignKey(Person, on_delete=models.CASCADE)
    # company_owner = models.ForeignKey(Company, on_delete=models.CASCADE)

    class Meta:
        """Metaclass for Contact class."""

        verbose_name = 'contact'
        verbose_name_plural = 'contacts'
        abstract = True


class Person(Contact):
    """Main Person Model."""

    SALUTATION_CHOICES = (
        ('MR', 'Mister'),
        ('MS', 'Miss'),
        ('DR', 'Doctor'),
        ('PhD', 'Professor'),
        ('LW', 'Lawyer')
    )

    salutation = models.CharField(max_length=3, choices=SALUTATION_CHOICES, blank=True)
    first_name = models.CharField('first name', max_length=24)
    middle_name = models.CharField('middle name', max_length=24, blank=True)
    last_name = models.CharField('last name', max_length=24)

    rec_date = models.DateTimeField('date recorded')

    class Meta:
        """Meta class for Person class."""

        verbose_name = 'person'
        verbose_name_plural = 'persons'

    def __str__(self):
        """Return Person's full name."""
        return '%s %s %s' % (self.first_name, self.middle_name, self.last_name)


class Company(Contact):
    """Main Company Model."""

    company_name = models.CharField('company name', max_length=250)

    # company_rec_date = models.DateTimeField('date recored', auto_now_add=True)

    class Meta:
        """Meta class for Company class."""

        verbose_name = 'company'
        verbose_name_plural = 'companies'

    def __str__(self):
        """Return company name."""
        return self.company_name

contacts/views.py
# Django
from django.shortcuts import render
from django.views import generic

# Local
from .models import Person, Company


# Create your views here.
def index(request):
    """Main index view."""
    return render(request, 'contacts/index.html')


class PersonList(generic.ListView):
    """ListView for Contacts."""

    model = Person
    # template_name = 'contacts/contacts.html'
    context_object_name = 'contact_list'

    def get_context_data(self, **kwargs):
        """Get model fields for table view."""
        context = super().get_context_data(**kwargs)
        context['field_list'] = Person._meta.get_fields()
        return context


class PersonDetail(generic.DetailView):
    """DetailView for Persons."""

    model = Person


class CompanyList(generic.ListView):
    """ListView for Companies."""

    model = Company
    context_object_name = 'company_list'

    def get_context_data(self, **kwargs):
        """Get model fields for table view."""
        context = super().get_context_data(**kwargs)
        context['field_list'] = Company._meta.get_fields()
        return context


class CompanyDetail(generic.DetailView):
    """CompanyDetail for Company."""

    model = Company

contacts/templates/contacts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}Gıdasist CRM{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'contacts/dashboard.css' %}"  />
  </head>
  <body>
    <header id="dashboard-header">
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="#">Gıdasist CRM</a>
        <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="gsistcrm-navbar">
          <ul class="navbar-nav mr-auto">
            <li class="collapse navbar-collapse" id="navbarsExampleDefault">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="collapse navbar-collapse" id="navbarsExampleDefault">
              <a class="nav-link" href="{% url 'contacts:person' %}">Persons</a>
            </li>
            <li class="collapse navbar-collapse" id="navbarsExampleDefault">
              <a class="nav-link" href="{% url 'contacts:company' %}">Company</a>
            </li>
          </ul>
          <form class="form-inline mt-2 mt-md-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
    </header>
    {% block content %}{% endblock %}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>

contacts/templates/contacts/company_list.html
{% extends "contacts/base.html" %}

{% block content %}
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      {% for field in field_list %}
        <th>{{ field.verbose_name }}</th>
      {% endfor %}
    </thead>
    <tbody>
      {% for company in company_list %}
        <a href="{% url 'contacts:companydetail' company.pk %}">
          <tr>
            <td />
            <td>{{ company.id }}</td>
            <td>{{ company.first_name }}</td>
            <td>{{ company.middle_name }}</td>
            <td>{{ company.last_name }}</td>
            <td>{{ company.rec_date }}</td>
            <td>{{ company.email }}</td>
          </tr>
        </a>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

contacts/templates/contacts/contacts.html
{% extends "contacts/base.html" %}

{% block content %}

{% if objects %}
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        {% for field in fields %}
          <th>{{ field.verbose_name }}</th>
        {% endfor %}
      </thead>
      <tbody>
        {% for contact in objects %}
          <tr>
            <td />
            <td>{{ contact.id }}</td>
            <td>{{ contact.first_name }}</td>
            <td>{{ contact.middle_name }}</td>
            <td>{{ contact.last_name }}</td>
            <td>{{ contact.rec_date }}</td>
            <td>{{ contact.email }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endif %}

{% endblock %}

contacts/templates/contacts/index.html
{% extends "contacts/base.html" %}

contacts/templates/contacts/person_list.html
{% extends "contacts/base.html" %}

{% block content %}
<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
      {% for field in field_list %}
        <th>{{ field.verbose_name }}</th>
      {% endfor %}
    </thead>
    <tbody>
      {% for contact in contact_list %}
        <a href="{% url 'contacts:persondetail' contact.pk %}">
          <tr>
            <td />
            <td>{{ contact.id }}</td>
            <td>{{ contact.first_name }}</td>
            <td>{{ contact.middle_name }}</td>
            <td>{{ contact.last_name }}</td>
            <td>{{ contact.rec_date }}</td>
            <td>{{ contact.email }}</td>
          </tr>
        </a>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}